#!/usr/bin/env node
// sync-agents.mjs — fan one tool-neutral agent/skill definition out to every harness.
//
//   SOURCE (edit these)            GENERATED (never edit; commit them)
//   agents/manifest.json           .claude/agents/<name>.md      Claude Code subagents
//   agents/<name>.md               .codex/agents/<name>.toml     Codex custom agents
//   skills/<name>/SKILL.md         .agents/skills/<name>/SKILL.md  Antigravity roles-as-skills
//                                  .claude/skills/<n>/SKILL.md
//                                  .codex/skills/<n>/SKILL.md
//                                  .agents/skills/<n>/SKILL.md
//
// Usage:  node scripts/sync-agents.mjs [--check]
//         --check exits 1 if anything on disk is stale (for CI / pre-commit).

import { readFileSync, writeFileSync, mkdirSync, readdirSync, rmSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');
const BANNER = 'GENERATED by scripts/sync-agents.mjs — edit agents/ or skills/ instead, then re-run.';
// Antigravity caps every rules/skill file at 12,000 characters — fail loudly rather
// than silently emitting a file it will truncate.
const ANTIGRAVITY_LIMIT = 12000;

const manifest = JSON.parse(readFileSync(join(ROOT, 'agents/manifest.json'), 'utf8'));
const stale = [];

function emit(relPath, content) {
  if (relPath.startsWith('.agents/') && content.length > ANTIGRAVITY_LIMIT)
    throw new Error(`${relPath} is ${content.length} chars — Antigravity caps rules files at ${ANTIGRAVITY_LIMIT}. Split detail out and link to it.`);
  const abs = join(ROOT, relPath);
  const prev = existsSync(abs) ? readFileSync(abs, 'utf8') : null;
  if (prev === content) return;
  if (CHECK) { stale.push(relPath); return; }
  mkdirSync(dirname(abs), { recursive: true });
  writeFileSync(abs, content);
  console.log(`  wrote ${relPath}`);
}

// Wipe generated agent files that no longer have a source, so a rename doesn't leave a ghost.
function prune(dir, keep, ext) {
  const abs = join(ROOT, dir);
  if (!existsSync(abs)) return;
  for (const f of readdirSync(abs)) {
    if (!f.endsWith(ext) || keep.has(f.slice(0, -ext.length))) continue;
    if (CHECK) { stale.push(`${dir}/${f} (orphan)`); continue; }
    rmSync(join(abs, f));
    console.log(`  removed ${dir}/${f}`);
  }
}

const names = new Set(manifest.agents.map((a) => a.name));

for (const a of manifest.agents) {
  const body = readFileSync(join(ROOT, `agents/${a.name}.md`), 'utf8').trimEnd();

  // ── Claude Code: YAML frontmatter. JSON.stringify gives a valid double-quoted
  //    YAML scalar, which is what the multi-line `ops` description needs.
  const cl = a.claude ?? {};
  const yaml = [
    '---',
    `name: ${a.name}`,
    `description: ${JSON.stringify(a.description)}`,
    cl.tools ? `tools: ${cl.tools}` : null,
    cl.model ? `model: ${cl.model}` : null,
    '---',
  ].filter(Boolean).join('\n');
  emit(`.claude/agents/${a.name}.md`, `${yaml}\n\n<!-- ${BANNER} -->\n\n${body}\n`);

  // ── Codex: one TOML per agent. Literal ''' strings need no escaping at all.
  for (const [k, v] of Object.entries({ description: a.description, developer_instructions: body })) {
    if (v.includes("'''")) throw new Error(`${a.name}.${k} contains ''' — cannot emit as a TOML literal string`);
  }
  const cx = a.codex ?? {};
  const toml = [
    `# ${BANNER}`,
    '',
    `name = "${a.name}"`,
    `description = '''\n${a.description}\n'''`,
    ...Object.entries(cx).map(([k, v]) => `${k} = ${JSON.stringify(v)}`),
    '',
    `developer_instructions = '''\n${body}\n'''`,
  ].join('\n');
  emit(`.codex/agents/${a.name}.toml`, `${toml}\n`);

  // ── Antigravity: no file-based subagent primitive (`agy agents` reads a server-side
  //    list, not the repo). Roles become skills — verified against agy 1.1.22, whose
  //    builtin `migrate-workflows` skill states `.agents/workflows/*.md` is DEPRECATED in
  //    favour of `.agents/skills/<name>/SKILL.md`, which gives both `/name` slash
  //    invocation and semantic auto-discovery. Rules files are capped at 12k chars.
  const skill = [
    '---',
    `name: ${a.name}`,
    `description: ${JSON.stringify(a.description.split('\n')[0])}`,
    '---',
    '',
    `<!-- ${BANNER} -->`,
    '',
    `# ${a.name}`,
    '',
    'Adopt the role below for this task. Read `AGENTS.md` in the workspace root first — it is the shared operating contract; this file only adds the role.',
    '',
    '---',
    '',
    body,
  ].join('\n');
  emit(`.agents/skills/${a.name}/SKILL.md`, `${skill}\n`);
}

prune('.claude/agents', names, '.md');
prune('.codex/agents', names, '.toml');

// `.agents/workflows/` is deprecated by Antigravity — remove it if an older sync left one.
{
  const wf = join(ROOT, '.agents/workflows');
  if (existsSync(wf)) {
    if (CHECK) stale.push('.agents/workflows (deprecated, should be removed)');
    else { rmSync(wf, { recursive: true }); console.log('  removed .agents/workflows (deprecated)'); }
  }
}

// ── Skills: identical SKILL.md format across all three, so this is a fan-out copy.
for (const s of manifest.skills ?? []) {
  const src = readFileSync(join(ROOT, `skills/${s}/SKILL.md`), 'utf8');
  for (const d of ['.claude/skills', '.codex/skills', '.agents/skills']) {
    emit(`${d}/${s}/SKILL.md`, src);
  }
}

if (CHECK && stale.length) {
  console.error('Stale generated files — run `node scripts/sync-agents.mjs`:');
  for (const f of stale) console.error(`  ${f}`);
  process.exit(1);
}
console.log(CHECK ? 'agent config is in sync.' : 'sync complete.');
